
drop table app_test if exists;
create table app_test (
    id int generated by default as identity,
    cnt varchar(255) ,
    deleted char(1),
    primary key (id)
);

drop table app_test_0 if exists;
create table app_test_0 (
    id int generated by default as identity,
    cnt varchar(255) ,
    deleted char(1),
    primary key (id)
);

drop table app_test_1 if exists;
create table app_test_1 (
    id int generated by default as identity,
    cnt varchar(255) ,
    deleted char(1),
    primary key (id)
);

DROP SEQUENCE SEQ_APP_TEST_ID if exists;
CREATE SEQUENCE SEQ_APP_TEST_ID;